### ISSUE TITLE
Weird problem when not chaining pipe()s.

### ISSUE THREAD

**Issue by AlicanC** [OverZealous/lazypipe#13]
In the example below, there are two ways I tried to do the same thing.

```javascript
var gulp = require('gulp');
var lazypipe = require('lazypipe');
var newer = require('gulp-newer');
var less = require('gulp-less');
var rename = require('gulp-rename');

// start crashing lines
var lp = lazypipe();

lp.pipe(newer, {dest: 'build', ext: '.css'});

lp.pipe(less)
    .pipe(rename, {extname: '.css'});
// end crashing lines

//start working lines
var lp = lazypipe()
    .pipe(newer, {dest: 'build', ext: '.css'})
    .pipe(less)
    .pipe(rename, {extname: '.css'});
//end working lines

gulp.task('default', function () {
    return gulp.src('src/*.less')
        .pipe(lp())
        .pipe(gulp.dest('build'));
});
```

When I chain the `pipe()` calls, I get no errors. (I'm not saying that it "works". I'm actually trying to see why `gulp-newer` doesn't do what it should at the moment.) When I store the result of `lazypipe()` and use it, I get this error:

```
_\test>gulp
[23:05:31] Using gulpfile _\test\Gulpfile.js
[23:05:31] Starting 'default'...
[23:05:31] 'default' errored after 4.42 ms
[23:05:31] Error: Tried to build a pipeline with no pipes!
    at validateSteps (_\node_modules\lazypipe\index.js:17:10)
    at build (_\node_modules\lazypipe\index.js:25:5)
    at Gulp.<anonymous> (_\test\Gulpfile.js:21:15)
    at module.exports (_\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (_\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (_\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (_\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at &\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
```

**Comment by OverZealous** [comment]
Every time you call `.pipe()`, lazypipe returns a new object.

```js
var lp = lazypipe() // empty pipe
             .pipe(foo) // pipe containing foo
             .pipe(bar) // pipe containing foo->bar
```

If you don't chain the calls, you have to do this:

```js
lp = lp.pipe(...);
lp = lp.pipe(...);
```

You are getting an error because you are basically taking the original object (which had no pipes) and trying to use it.  This is no different than using `gulp.src().pipe().pipe()`.

**Comment by AlicanC** [comment]
Does this behavior come from lazypipe or does it go all the way back to Node.js streams? I would think that I'm right to expect to get the same object returned when I'm chaining methods.

**Comment by OverZealous** [comment]
This has nothing to do with node streams: Lazypipe allows you to create reusable streams.  It builds them in the last step.  To be reusable, they have to work the way they do.

If lazypipe wasn't built the way it is, you couldn't do something like this:

```js

var fooBase = lazypipe().pipe(A).pipe(B);

var fooDev = fooBase.pipe(C).pipe(D);

var fooProd = fooBase.pipe(E).pipe(F);
```

If you always had the same object, then `fooBase` wouldn't be reusable, and there would be no point to lazypipe.

Sorry you made an assumption, but nothing in the code (it's a small, open-source library) or documentation should make you assume it works that way.
