### ISSUE TITLE
Merging multiple sources for a pipe?

### ISSUE THREAD

**Issue by kokujin** [OverZealous/lazypipe#16]
I am trying to:

1. Concat and compress a set of CSS files 
2. Inject both the compressed and non-compressed files in a HTML template( prod/dev template conditional, if ("dev")... )

I have this so far
`````
return lazypipe()
    .pipe(gulp.dest, output.non_compressed_path)
    .pipe(plugins.concat, optionsObj.filename)
    .pipe(plugins.csso, true)
    .pipe(gulp.dest, output.compressed_path)
````
To Inject the above in HTML templates however, the lazypipe source would have to start with the HTML template, so piping the result of the above would not work as in:

`````
  // This has to starte with "gulp.src(templateName)" then pipe to below
 .pipe(plugins.inject, gulp.src(cssFiles, {read: false}), {name: 'test'})
...
````

Can someone point me in the right direction? Thanks

**Comment by OverZealous** [comment]
I'm sorry, but this isn't a support forum for gulp.  Please try searching online for "gulp merge".
