### ISSUE TITLE
Complex Lazypipe channel with several sources and outputs? 

### ISSUE THREAD

**Issue by kokujin** [OverZealous/lazypipe#17]
Trying this again, the original issue was closed abruptly.

The assumption that my question is a "Gulp" issue is wrong @OverZealous , in fact, I posted code that clearly uses lazypipe.

I can merge streams using either the merge or event-stream libraries, thats not the issue. At the moment I am using a simple function as a re-usable unit for the several Gulp tasks. This has been in use for several months. I thought it would be nice to use Lazypipe which was developed to be used as reusable units/ channels.

My question is; How can I create a reusable lazypipe channel for a complex task that I would like to use in several projects.

I am trying to:

**1. Concat and compress a set of CSS files
2. Inject both the compressed and non-compressed files in a HTML template
3. Make this a usable lazypipe channel for re-use over a set of projects**

I have this so far

````
return lazypipe()
    .pipe(gulp.dest, output.non_compressed_path)
    .pipe(plugins.concat, optionsObj.filename)
    .pipe(plugins.csso, true)
    .pipe(gulp.dest, output.compressed_path)
`````
To Inject the above in HTML templates however, the lazypipe source would have to start with the HTML template, so piping the result of the above would not work as in:

````
  // This has to starte with "gulp.src(templateName)" then pipe to below
 .pipe(plugins.inject, gulp.src(cssFiles, {read: false}), {name: 'test'})````
`````
Can someone point me in the right direction? Thanks

**Comment by OverZealous** [comment]
There is no "someone", there is only me.  This is my project, I'm the sole maintainer.  I don't know why you think this is a public forum for support.  Try StackOverflow if you want answers to this sort of question.

This is **not** a lazypipe issue, it's not an issue at all.

**Comment by kokujin** [comment]
Jeez, I have already decided on using the async lib instead this morning. Thanks for nothing.
