### ISSUE TITLE
Using gulp.src().on

### ISSUE THREAD

**Issue by mikehaas763** [OverZealous/lazypipe#20]
I saw #4 but it didn't help me to find a solution. I'm using lazypipe to create reusable pieces of functionality that can be packaged up and reused. Is this the proper way to use lazy pipe with .on()?

```javascript
function babelPipe(config) {
    var jsFilter = gulpFilter(['**/*.js'], {restore: true});

    var pipe = lazypipe()
        .pipe(function() {
            return jsFilter;
        })
        .pipe(babel)
        .pipe(function() {
            return jsFilter.restore;
        });

    return pipe()
        .on('error', function(e) {
            console.log('>>> ERROR', e);
            // emit here
            this.emit('end');
        });
}
```

**Comment by OverZealous** [comment]
Lazypipe isn't doing anything here.  If you are wrapping the code in a function anyway, then just return the pipe from the function.

Lazypipe just makes it easier to create reusable partial streams without wrapping them in functions.

You could replace your whole thing with:

```js
function babelPipe(config) {
    return gulpFilter(['**/*.js'], {restore: true})
        .pipe(babel())
        .pipe(jsFilter.restore)
        .on('error', function(e) {
            console.log('>>> ERROR', e);
            // emit here
            this.emit('end');
        });
}
```

**Comment by mikehaas763** [comment]
I guess what I was thinking was just using Lazypipe to create the pipe in the first place and I didn't realize the gulp-filter plugin function created a pipe stream for me.
