### ISSUE TITLE
Using with gulp-sass 

### ISSUE THREAD

**Issue by Bnaya** [OverZealous/lazypipe#21]
Hey

I'm trying to refactor my gulp to use this tool
sass pipeline looks like:
```js
gulp.task('sass', function () {
  gulp.src('./sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./css'));
});
```
And i couldn't figure i i can add the .on('error', sass.logError)

Thanks!

**Comment by OverZealous** [comment]
Just wrap your pipe in a function.  There [are examples in the docs.](https://github.com/OverZealous/lazypipe#using-with-more-complex-function-arguments-such-as-gulp-if)

**Comment by leojin** [comment]
For Example
```javascript
var sassOpt = {
    includePaths: [pathInclude]
}
var pipeInsScss = lazypipe()
    .pipe(function (opt, cb) {
        return $$.sass(opt).on('error', cb);
    }, scssOpt, $$.sass.logError);
```
