### ISSUE TITLE
How to use lazypipe() with gulp-replace?

### ISSUE THREAD

**Issue by konstantin-petlya** [OverZealous/lazypipe#28]
Hi.

I have the problem with one WP theme ('Sage') which use lazypipe.
Here is [the root of problem](https://github.com/nodejs/help/issues/429) (it isn't related with lazypipe).
But gulp-sass v.2.3.2 didn't install normal to my Windows10x64 PC, so I want to use the ugly hack: "I also replaced & with #{"&"} in the mixin and now it seems to work fine."

`.pipe(replace, '&:', '#{&}:')`

**How to replace all '&:' '#{&}:' before running all others pipe() in this theme's gulp function?** 

```
var cssTasks = function (filename) {
    return lazypipe()
    .pipe(function () {
      return gulpif(!enabled.failStyleTask, plumber());
    })
    .pipe(function () {
      return gulpif(enabled.maps, sourcemaps.init());
    })
    .pipe(replace, '&:', '#{&}:') // (!) looks like don't work - the error is present
    .pipe(function () {
      return gulpif('*.scss', sass({
        outputStyle: 'nested', // libsass doesn't support expanded yet
        precision: 10,
        includePaths: ['.'],
        errLogToConsole: !enabled.failStyleTask
      }));
    })
    .pipe(concat, filename)
    .pipe(autoprefixer, {
      browsers: [
        'last 2 versions',
        'ie 9',
        'android 4'
      ]
    })
    .pipe(minifyCss, {
      advanced: false,
      rebase: false
    })
    .pipe(function () {
      return gulpif(enabled.rev, rev());
    })
    .pipe(function () {
      return gulpif(enabled.maps, sourcemaps.write('.'));
    })();
};
```

Context is:
```gulp.task('styles', ['wiredep'], function () {
  var merged = merge();
  manifest.forEachDependency('css', function (dep) {
    var cssTasksInstance = cssTasks(dep.name);
    if (!enabled.failStyleTask) {
      cssTasksInstance.on('error', function (err) {
        console.error(err.message);
        this.emit('end');
      });
    }
    merged.add(gulp.src(dep.globs, {base: 'styles'})
      .pipe(cssTasksInstance));
  });
  return merged
    .pipe(writeToManifest('styles'));
});
```

**Comment by OverZealous** [comment]
Can you please reformat your comment using triple backticks (` ``` `), so I can read the pipes.

**Comment by konstantin-petlya** [comment]
Sorry. I edited my question.

**Comment by OverZealous** [comment]
Are you trying to replace something _before_ or _after_ Sass? Because you have the replace happening before, which means you could just change your source files.

**Comment by konstantin-petlya** [comment]
Before any tasks related to *.scss files. Source files are the whole sass bootstrap & all custom scss files. I don't want to have #{&} in source files. Just replace '&' to '#{&}' in files on the fly (on the gulp pipe). In the future, when the bug will be fixed, I could delete this pipe-fix.

**Comment by OverZealous** [comment]
Given that, this doesn't seem to have anything to do with lazypipe—I'm not even sure lazypipe is necessary in this setup, since the pipe could just be a normal Gulp pipe (it's even already wrapped in a function).

If you want to try to figure it out, I'd say make minimal example case to see if it works:

1. Without lazypipe. Just feed your source file in, then through your replacement, then view the output. Assuming this works, then
2. Try the same thing wrapped in a lazypipe.

The only reason you might have an issue is with Streams2, which has sometimes caused issues before.

**Comment by OverZealous** [comment]
Closing as there's been no feedback in a long while.
