### ISSUE TITLE
Getting rid of event-stream as devDependency

### ISSUE THREAD

**Issue by abelski21** [OverZealous/lazypipe#29]
Can we get rid the dependency for event-stream? There is a recent malicious attack on this [dominictarr/event-stream#116](https://github.com/dominictarr/event-stream/issues/116). We can lock the version to event-stream@3.3.4.

**Comment by OverZealous** [comment]
Published as 1.0.2, with a locked `event-stream` and updated Mocha, and no audit errors.

Thanks for the report!
