### ISSUE TITLE
Wrap and passings args?

### ISSUE THREAD

**Issue by ddarbyson** [OverZealous/lazypipe#8]
Is there a simple way to wrap lazypipe in a function and pass an argument?

I have for example:

``` js
var CSS = lazypipe()
  .pipe(size, { showFiles: true, title: 'css' })
  .pipe(gulp.dest, './build/css');
  .pipe(minifycss)
  .pipe(rename, { suffix: '.min' })
  .pipe(size, { showFiles: true, title: 'css' })
  .pipe(gulp.dest, './build/css');
```

however, i'd like `./build/css` to be passed with an argument. Any suggestions are appreciated.

**Comment by gligoran** [comment]
This should really be in the docs, especially for people like me, that don't really know streams that in-depth.

I got this far:

```js
function myPipe(arg) {
   return lazypipe().pipe(foo).pipe(bar, arg);
}
```

but didn't know I have to call the whole thing at the end using ```()```.
